//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorSystem.ServiceReference3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasicDetails", Namespace="http://schemas.datacontract.org/2004/07/MonitorSystem")]
    [System.SerializableAttribute()]
    public partial class BasicDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string basicidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string expire_sField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string expire_tField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string basicid {
            get {
                return this.basicidField;
            }
            set {
                if ((object.ReferenceEquals(this.basicidField, value) != true)) {
                    this.basicidField = value;
                    this.RaisePropertyChanged("basicid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string expire_s {
            get {
                return this.expire_sField;
            }
            set {
                if ((object.ReferenceEquals(this.expire_sField, value) != true)) {
                    this.expire_sField = value;
                    this.RaisePropertyChanged("expire_s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string expire_t {
            get {
                return this.expire_tField;
            }
            set {
                if ((object.ReferenceEquals(this.expire_tField, value) != true)) {
                    this.expire_tField = value;
                    this.RaisePropertyChanged("expire_t");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertBasicDetails", ReplyAction="http://tempuri.org/IService1/InsertBasicDetailsResponse")]
        string InsertBasicDetails(MonitorSystem.ServiceReference3.BasicDetails BasicInfo, string rd, string wrt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUpdatedBasic", ReplyAction="http://tempuri.org/IService1/GetUpdatedBasicResponse")]
        string GetUpdatedBasic(MonitorSystem.ServiceReference3.BasicDetails BasicInfoEdit, string Editrd, string Editwrt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBasicInfo", ReplyAction="http://tempuri.org/IService1/DeleteBasicInfoResponse")]
        string DeleteBasicInfo(string BasicId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBasicInfoById", ReplyAction="http://tempuri.org/IService1/getBasicInfoByIdResponse")]
        string getBasicInfoById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAll", ReplyAction="http://tempuri.org/IService1/getAllResponse")]
        MonitorSystem.ServiceReference3.BasicDetails[] getAll();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MonitorSystem.ServiceReference3.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MonitorSystem.ServiceReference3.IService1>, MonitorSystem.ServiceReference3.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertBasicDetails(MonitorSystem.ServiceReference3.BasicDetails BasicInfo, string rd, string wrt) {
            return base.Channel.InsertBasicDetails(BasicInfo, rd, wrt);
        }
        
        public string GetUpdatedBasic(MonitorSystem.ServiceReference3.BasicDetails BasicInfoEdit, string Editrd, string Editwrt) {
            return base.Channel.GetUpdatedBasic(BasicInfoEdit, Editrd, Editwrt);
        }
        
        public string DeleteBasicInfo(string BasicId) {
            return base.Channel.DeleteBasicInfo(BasicId);
        }
        
        public string getBasicInfoById(string Id) {
            return base.Channel.getBasicInfoById(Id);
        }
        
        public MonitorSystem.ServiceReference3.BasicDetails[] getAll() {
            return base.Channel.getAll();
        }
    }
}
